//This file tests the API endpoints for our Express.js app, responses will be given in the form of JSON data with status headers


@WebApiHost = http://localhost:5220


###
//add a user
POST {{WebApiHost}}/user/JohnSmith

###
//get all users
GET {{WebApiHost}}/user