//This file tests the API endpoints for our Express.js app, responses will be given in the form of JSON data with status headers


@WebApiHost = http://localhost:5220


###
//add a user
POST {{WebApiHost}}/user/SteveBrown

###

POST {{WebApiHost}}/timer/GrantRynders/https%3A%2F%2Fgithub.com%2FGrantRynders%2FGithub-Extension-Project%2Fissues%2F45/Calculate%20total%20time%20spent%20on%20an%20issue,%20and%20append%20it%20to%20the%20lgo
###
//get all users
GET {{WebApiHost}}/user

###
//get all issues
GET {{WebApiHost}}/issue

###
//get all Timer Periods
GET {{WebApiHost}}/timerperiod/GrantRynders/url/timeIstarted/timeIstopped

###
//get user by username
GET {{WebApiHost}}/user/JohnSmith

###
//get user by username and that user's timers
GET {{WebApiHost}}/timermodel/timerperiod

###

GET {{WebApiHost}}/issuemodel/1/timespentbyuser

###

GET {{WebApiHost}}/timerperiod